### PR TITLE
propagating alternative cause if it's not checked

### LINKED ISSUE #911: Can't catch specific exception in Interceptor
```
@AroundCall
    public void intercept(SimpleInterceptorStack stack) throws InterceptionException {
        try {
            stack.next();
        } catch (MyException e) {
            System.out.println("error");
        } 
    }
```

This code does not work because VRaptor is encapsulating `MyException` in one `ApplicationLogicException`.

### PR DESCRIPTION
**Pull request by Turini**
As suggested by @lucascs [here](https://github.com/caelum/vraptor4/issues/911#issuecomment-67262416). Closes #911.

It breaks compatibility, but we're going to `4.2` and it'll be very highlighted 
on release notes. I'll add some docs before merging it. What do you think?

### CODE REVIEW

File: vraptor-core/src/main/java/br/com/caelum/vraptor/observer/ExecuteMethodExceptionHandler.java [hunk 1]
```diff
@@ -17,7 +20,8 @@
 	private final static Logger log = getLogger(ExecuteMethodExceptionHandler.class);
 
 	public void handle(Exception exception) {
-		if (exception instanceof IllegalArgumentException) {
+		if (exception instanceof IllegalArgumentException
+				|| exception instanceof IllegalStateException) {
```
Comment (lucascs) [inline vraptor-core/src/main/java/br/com/caelum/vraptor/observer/ExecuteMethodExceptionHandler.java]: I'm almost tending to use VRaptor specific exceptions for this case, instead of reusing IllegalArg and IllegalState...

We're doing this only because of validations, right? 
We could create a ValidationFailedException.

**Comment by nykolaslima** [comment]
Look good to me. I just didn't understand why we are wrapping `IllegalArgumentException` and `IllegalStateException`. Can you help me to understand it?

**Comment by Turini** [comment]
about the `IllegalStateException`, that's because VRaptor throws it when user
didn't specify what to do when an validation error happens. In that case makes
sense for me throw `ValidationFailedException` instead, as @lucascs just said.

**Comment by Turini** [comment]
guys, telling the truth, I've no idea why we wrap the `IllegalArgumentException` 
as `InterceptorException`. Looking our code it doesn't make sense for me now.

does anyone know why we're doint it? (and looking here, VRaptor 3 wrap it too)

**Comment by nykolaslima** [comment]
If there is no reason, can't we just create the new exception as you guys suggested?

**Comment by Turini** [comment]
yes, if truly there is no reason (I guess, not sure), we can refactor it removing 
the `if` and using the new validation error exception proposed. I'd be nice, 
but lets wait a while to see if anyone knows the reason, before refactoring it :)

**Comment by nykolaslima** [comment]
:+1:

**Comment by lucascs** [comment]
I don't remember the reason, but I see no harm in doing it.

I just looked at the file history on VRaptor 3, and these catches went back to early 2009, first versions of VRaptor.

Remove it, and we let people test it and see if some bugs appear, but I don't see why it would happen.

**Comment by Turini** [comment]
:happy_panda:

**Comment by Turini** [comment]
I've updated my PR. What do you think?

**Comment by nykolaslima** [comment]
:+1:

**Comment by lucascs** [comment]
:ship:

**Comment by nykolaslima** [comment]
:heart_eyes:
