### PR TITLE
loading properties in bean construction

### LINKED ISSUE #972: Problem in environment with concurrent access
When you use the `Environment` for the first time, it tries to initialize in a lazy mode.

The problem is that if we have concurrent threads trying to access the `Environment`, this line could lead to `NoSuchKeyException` because the second thread will use an empty `Property` object.
https://github.com/caelum/vraptor4/blob/d5adfda037461d84c1a2a5d1c169b4a986371313/vraptor-core/src/main/java/br/com/caelum/vraptor/environment/DefaultEnvironment.java#L80

We could resolve this by making the lazy initialization syncronized. There is another better solution to this?

(@csokol identified the problem, thanks Chico)

### PR DESCRIPTION
**Pull request by nykolaslima**
Fixes #972

This avoid concurrent access that could lead to errors in multithread environments.

@Turini @csokol I believe that we don't need to use the `@PostContruct` because we can do it in `DefaultEnvironment`'s constructor. What do you think about it?

### CODE REVIEW

**Comment by Turini** [comment]
@nykolaslima, your code looks nice! However, I'd consider using `@PostConstruction` 
because it's considered a good pratice (we have the guarantee that it'll run a single time 
and that it will happen after the class has being successfully initialized). What you think?

**Comment by Turini** [comment]
And looks like travis build failed. Could you check if this change broke some tests?

**Comment by nykolaslima** [comment]
Ok @Turini I'll change it to use `@PostConstruct` :+1:

**Comment by nykolaslima** [comment]
@Turini Done :tada:

**Comment by nykolaslima** [comment]
The Travis build is broken. I'm going to check it out

**Comment by nykolaslima** [comment]
@Turini the problem is that VRaptor's tests are instantiating `DefaultEnvironment` manually and this way the `@PostConstruct` don't got called.

Do you know the best approach to solve this?

**Comment by nykolaslima** [comment]
Using constructor, we also guarantee that it will run a single time, don't we?

If so, maybe this could be a better approach in order to avoid this problem with unit tests.

**Comment by csokol** [comment]
I think you can simply call the annotated method during test setup. Or you
could use the runner that inject cdi stuff to tests (but I think it's
overkill in that case).

**Comment by nykolaslima** [comment]
Ok @csokol, I think you are right. Doing this!

**Comment by nykolaslima** [comment]
@Turini @csokol done guys :ship:

File: vraptor-core/src/test/java/br/com/caelum/vraptor/environment/DefaultEnvironmentTest.java [hunk 1]
```diff
@@ -137,11 +138,26 @@ public void shouldUseSystemPropertiesWhenSysenvIsntPresent() {
...
 		System.setProperty("env_name", "customEnv");
 		String value = defaultEnvironment.get("env_name");
 		assertThat("customEnv", is(value));
 		//unset property to not break other tests
 		System.setProperty("env_name", "");
 	}
+	
+	private DefaultEnvironment buildEnvironment(EnvironmentType environmentType) {
+		DefaultEnvironment defaultEnvironment = new DefaultEnvironment(environmentType);
+		defaultEnvironment.setup();
```
Comment (Turini) [inline vraptor-core/src/test/java/br/com/caelum/vraptor/environment/DefaultEnvironmentTest.java]: you don't need to do that if you're already calling `loadProperties` in the public constructor, right? https://github.com/caelum/vraptor4/pull/973/files#diff-b7b62c45c7478eb642acfb81c12a4227R82

Comment (nykolaslima) [inline vraptor-core/src/test/java/br/com/caelum/vraptor/environment/DefaultEnvironmentTest.java]: My bad, I'll remove it.

**Comment by nykolaslima** [comment]
@Turini done!

**Comment by Turini** [comment]
lumpa! let's just wait a while for more reviews, but it sounds good to :rocket:

**Comment by nykolaslima** [comment]
Thanks. I think this issue should be treated as a emergencial release, if multiple threads hit the application when it's just started, this bug could lead to broken `@ApplicationScoped` beans if they depend on `@RequestScoped` beans. The application could stop serving because of this.

What do you think?

**Comment by Turini** [comment]
Sure, you're right! I intend to do a new release asap, including this PR.

**Comment by Turini** [comment]
thks @nykolaslima, it will be released tomorrow!
