### PR TITLE
InstantiateObserver must be dependent

### LINKED ISSUE #977: IllegalArgumentException on forward
I have the following Controllers

```java


@Controller
public class IndexController {
	private final Result result;

	@Deprecated // CDI eyes only
	public IndexController() {
		this(null);
	}

	@Inject
	public IndexController(Result result) {
		this.result = result;
	}

	@Path("/")
	public void index() {
        result.forwardTo("/page");
//      result.forwardTo(PageController.class).page();
    }
}
```
```java
@Controller
public class PageController {

	private final Result result;

	@Deprecated // CDI eyes only
	public PageController() {
		this(null);
	}

	@Inject
	public PageController(Result result) {
		this.result = result;
	}

	@Path("/page")
	public void page() {
        System.out.println("page");
    }
}
```

I try to forward (not redirect) from Index to Page controller. 
When i use `result.forwardTo(PageController.class).page(); ` forward works fine.
When i use `result.forwardTo("/page");` i get the following exception

```
javax.servlet.ServletException: java.lang.RuntimeException: br.com.caelum.vraptor.InterceptionException: java.lang.IllegalArgumentException: method public void vtests.PageController.page() cannot be invoked on clazz vtests.IndexController$Proxy$_$$_WeldClientProxy
br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:127)
io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85)
io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61)
io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56)
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45)
io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:63)
io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70)
io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261)
io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:247)
io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:76)
io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:166)
io.undertow.server.Connectors.executeRootHandler(Connectors.java:197)
io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:759)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
```
Debugging the code i found that the exception is thrown in `br.com.caelum.vraptor.observer.ExecuteMethod#execute` at line

```java
Object result = new Mirror().on(instance).invoke().method(reflectionMethod).withArgs(parameters);
```
when mirror try to create an instance of  `net.vidageek.mirror.invoke.MethodHandlerByMethod`

```java
public MethodHandlerByMethod(final ReflectionProvider provider, final Object target, final Class<?> clazz, final Method method) {
    
    if (clazz == null) {
        throw new IllegalArgumentException("clazz cannot be null");
    }
    if (method == null) {
        throw new IllegalArgumentException("method cannot be null");
    }
    if (!method.getDeclaringClass().isAssignableFrom(clazz)) {
        throw new IllegalArgumentException("method " + method + " cannot be invoked on clazz " + clazz.getName());
    }
    this.provider = provider;
    this.target = target;
    this.clazz = clazz;
    this.method = method;
}
```

### PR DESCRIPTION
**Pull request by Turini**
Closes #977

### CODE REVIEW

File: vraptor-core/src/main/java/br/com/caelum/vraptor/observer/InstantiateObserver.java [hunk 1]
```diff
@@ -58,7 +52,7 @@ public void instantiate(@Observes ControllerFound event) {
 		this.controllerInstance = new DefaultControllerInstance(instance);
 	}
 
-	@Produces @RequestScoped
+	@Produces @Dependent
 	public ControllerInstance getControllerInstance() {
```
Comment (Turini) [inline vraptor-core/src/main/java/br/com/caelum/vraptor/observer/InstantiateObserver.java]: this bean observes `ControllerFound` updating the controller instance, but since it was declared as request scoped, after a forward even firing the event, CDI was caching the old/first controller instance in the request scope.

Comment (lucascs) [inline vraptor-core/src/main/java/br/com/caelum/vraptor/observer/InstantiateObserver.java]: :cake:, a much better solution!

Comment (Turini) [inline vraptor-core/src/main/java/br/com/caelum/vraptor/observer/InstantiateObserver.java]: It was hard to find this problem :) thanks for your review
